// examples/react/src/MicrophoneSelector.tsx
import { useCallback, useState } from 'react'
import { useMicrophoneDeviceList } from './useMicrophoneDeviceList'

type MicrophoneSelectorProps = {
  onDeviceChange: (deviceId: string | null) => void
}

export const MicrophoneSelector = ({ onDeviceChange }: MicrophoneSelectorProps) => {
  const [selectedDevice, setSelectedDevice] = useState<string | null | undefined>(undefined)

  const handleDevicesChange = useCallback((nextDevices: Array<MediaDeviceInfo>) => {
    setSelectedDevice((current) => {
      if (nextDevices.length === 0) {
        if (current === undefined) return current
        onDeviceChange(null)
        return null
      }
      if (current === undefined || current === null) {
        const nextId = nextDevices[0]!.deviceId
        onDeviceChange(nextId)
        return nextId
      }
      return current
    })
  }, [onDeviceChange])

  const {
    devices,
    hasPermission,
    error,
    loading,
    getMicrophonePermission,
  } = useMicrophoneDeviceList({ onDevicesChange: handleDevicesChange })

  if (!hasPermission) {
    return (
      <div className="notice">
        <div>
          <div>Microphone access needed</div>
          <div>Please allow access to use voice features</div>
        </div>
        <button type="button" onClick={() => getMicrophonePermission()}>
          Grant Access
        </button>
      </div>
    )
  }

  return (
    <>
      <select
        value={selectedDevice ?? ''}
        onChange={(event) => {
          const deviceId = event.target.value || null
          setSelectedDevice(deviceId)
          onDeviceChange(deviceId)
        }}
      >
        {devices.map(device => (
          <option key={device.deviceId} value={device.deviceId}>
            {device.label}
          </option>
        ))}
      </select>
      {error && <div>{error}</div>}
      {loading && <div>Loading...</div>}
    </>
  )
}

// examples/vue/src/audio-recorder/MicrophoneSelector.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { getMicrophonePermission, useMicrophoneDeviceList } from './microphone-device-list'

export type MicrophoneSelectorEmits = {
  deviceChange: [deviceId: string | null]
}

const emit = defineEmits<MicrophoneSelectorEmits>()

const selectedDevice = ref<Nullable<string>>()
const setSelectedDevice = (deviceId: string | null) => {
  selectedDevice.value = deviceId
  emit('deviceChange', deviceId)
}

const onDevicesChangeCallback = (devices: Array<MediaDeviceInfo>) => {
  if (devices.length === 0) {
    // first time
    if (selectedDevice.value === undefined) return
    return setSelectedDevice(null)
  }
  if (selectedDevice.value === undefined) {
    // first time
    setSelectedDevice(devices[0]!.deviceId)
  }
  if (selectedDevice.value === null) {
    // Maybe some other logic
    setSelectedDevice(devices[0]!.deviceId)
  }
}

const {
  devices,
  hasPermission,
  error,
  loading,
} = useMicrophoneDeviceList({ onDevicesChange: onDevicesChangeCallback })

defineExpose({ selectedDevice })
</script>

<template>
  <div v-if="!hasPermission" class="notice">
    <div>
      <div>Microphone access needed</div>
      <div>Please allow access to use voice features</div>
    </div>
    <button type="button" @click="getMicrophonePermission">
      Grant Access
    </button>
  </div>

  <select v-else :value="selectedDevice" @change="setSelectedDevice(($event.target as HTMLSelectElement).value)">
    <option
      v-for="device in devices"
      :key="device.deviceId"
      :value="device.deviceId"
    >
      {{ device.label }}
    </option>
  </select>
  <div v-if="error">
    {{ error }}
  </div>
  <div v-if="loading">
    Loading...
  </div>
</template>
