// examples/react/src/MicrophoneStreamSelector.tsx
import { useState } from 'react'
import { getMicrophoneMediaStream, verifyAudioStream } from '../../shared/media-streams'
import { MicrophoneSelector } from './MicrophoneSelector'

type MicrophoneStreamSelectorProps = {
  attached: boolean
  onNewStream: (stream: MediaStream | null, error: unknown) => void
}

export const MicrophoneStreamSelector = ({ attached, onNewStream }: MicrophoneStreamSelectorProps) => {
  const [selectedDeviceId, setSelectedDeviceId] = useState<string | null>(null)
  const [lastDeviceStreamError, setLastDeviceStreamError] = useState<string | null>(null)
  const [attaching, setAttaching] = useState(false)

  const attachMicrophone = async () => {
    if (!selectedDeviceId) return
    setLastDeviceStreamError(null)
    setAttaching(true)

    try {
      const stream = await getMicrophoneMediaStream({ deviceId: selectedDeviceId })
      verifyAudioStream(stream)
      onNewStream(stream, null)
    }
    catch (error) {
      onNewStream(null, error)
      setLastDeviceStreamError(error instanceof Error ? error.message : 'Something went wrong while getting stream')
      console.error('Error while getting stream', error)
    }
    finally {
      setAttaching(false)
    }
  }

  const detachMicrophone = () => {
    setLastDeviceStreamError(null)
    onNewStream(null, null)
  }

  return (
    <>
      <div className="row">
        <MicrophoneSelector onDeviceChange={setSelectedDeviceId} />
        <button
          type="button"
          disabled={!selectedDeviceId || attaching}
          onClick={attachMicrophone}
        >
          Attach microphone
        </button>
        <button type="button" disabled={!attached} onClick={detachMicrophone}>
          Detach microphone
        </button>
      </div>
      {lastDeviceStreamError && <p className="error">{lastDeviceStreamError}</p>}
    </>
  )
}

// examples/vue/src/audio-recorder/MicrophoneStreamSelector.vue
<script lang="ts" setup>
import { ref } from 'vue'
import MicrophoneSelector from './MicrophoneSelector.vue'
import { getMicrophoneMediaStream, verifyAudioStream } from './stream.ts'

type MicrophoneStreamSelectorEmits = {
  newStream: [stream: MediaStream | null, error: null ] | [stream: null, error: unknown]
}

const { attached } = defineProps<{
  attached: boolean
}>()

const emit = defineEmits<MicrophoneStreamSelectorEmits>()

const selectedDeviceId = ref<Nullable<string>>(null)
const lastDeviceStreamError = ref<Nullable<string>>()
const attaching = ref(false)

const attachMicrophone = async () => {
  if (!selectedDeviceId.value) return
  lastDeviceStreamError.value = null
  attaching.value = true

  try {
    const stream = await getMicrophoneMediaStream({ deviceId: selectedDeviceId.value })
    verifyAudioStream(stream)
    emit('newStream', stream, null)
  }
  catch (e) {
    emit('newStream', null, e)
    lastDeviceStreamError.value = e instanceof Error ? e.message : 'Something went wrong while getting stream'
    console.error('Error while getting stream', e)
  }
  finally {
    attaching.value = false
  }
}

const detachMicrophone = () => {
  lastDeviceStreamError.value = null
  emit('newStream', null, null)
}
</script>

<template>
  <div class="row">
    <MicrophoneSelector @device-change="selectedDeviceId = $event" />
    <button type="button" :disabled="!selectedDeviceId || attaching" @click="attachMicrophone">
      Attach microphone
    </button>
    <button type="button" :disabled="!attached" @click="detachMicrophone">
      Detach microphone
    </button>
  </div>
  <p v-if="lastDeviceStreamError" class="error">
    {{ lastDeviceStreamError }}
  </p>
</template>
